#!/usr/bin/env bash
# Bash script that displays "To inifinity and beyond" indefinitely. With sleep 2 between each iteration. Displays "I am invicible!!!" when receiving a SIGTERM signal

trap "echo I am invincible!!!" 15

while : 
do 
    echo "To infinity and beyond"
    sleep 2
done 
