#!/usr/bin/env bash
# Displays "Holberton School" 10 times, but displays "Hi" on the 9th iteration
n=0
while [ $n -lt 10 ]
do
    echo "Holberton School"
    n=$(( n+1 ))
    if [[ "$n" == '9' ]]; then
    echo "Hi"
    fi
done
