#!/usr/bin/env bash
# Displays numbers from 1-20
# displays 4, and then "bad luck from China"
# displays 9, and then "bad luck from Japan"
# displays 17, and then "bad luck from Italy"

# must use while loop with case statement

n=1
while [ $n -le 20 ]

do
echo "$n"
((n++))

  case $n in
    "5" )
       echo "bad luck from China" ;;
    "10" )
       echo "bad luck from Japan" ;;
    "18" )
       echo "bad luck from Italy" ;;

esac

done
