#!/usr/bin/env bash
# Displays the content of the current directory in a list format. Only part of the name after the first dash is displayed.
Can only use for loop. Do not display hidden files

for list in *
do 
  echo "$list" | cut -d '-' -f 2
done
